# permissions to do viewer dendronautjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dendronautjob-viewer-role
rules:
- apiGroups:
  - batch.dendronaut.example.com
  resources:
  - dendronautjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.dendronaut.example.com
  resources:
  - dendronautjobs/status
  verbs:
  - get
