# permissions to do edit dendronautjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dendronautjob-editor-role
rules:
- apiGroups:
  - batch.dendronaut.example.com
  resources:
  - dendronautjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.dendronaut.example.com
  resources:
  - dendronautjobs/status
  verbs:
  - get
  - patch
  - update
