// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DendronautJob) DeepCopyInto(out *DendronautJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DendronautJob.
func (in *DendronautJob) DeepCopy() *DendronautJob {
	if in == nil {
		return nil
	}
	out := new(DendronautJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DendronautJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DendronautJobList) DeepCopyInto(out *DendronautJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DendronautJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DendronautJobList.
func (in *DendronautJobList) DeepCopy() *DendronautJobList {
	if in == nil {
		return nil
	}
	out := new(DendronautJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DendronautJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DendronautJobSpec) DeepCopyInto(out *DendronautJobSpec) {
	*out = *in
	in.Cron.DeepCopyInto(&out.Cron)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DendronautJobSpec.
func (in *DendronautJobSpec) DeepCopy() *DendronautJobSpec {
	if in == nil {
		return nil
	}
	out := new(DendronautJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DendronautJobStatus) DeepCopyInto(out *DendronautJobStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DendronautJobStatus.
func (in *DendronautJobStatus) DeepCopy() *DendronautJobStatus {
	if in == nil {
		return nil
	}
	out := new(DendronautJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DendronautTestResult) DeepCopyInto(out *DendronautTestResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DendronautTestResult.
func (in *DendronautTestResult) DeepCopy() *DendronautTestResult {
	if in == nil {
		return nil
	}
	out := new(DendronautTestResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DendronautTestResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DendronautTestResultList) DeepCopyInto(out *DendronautTestResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DendronautTestResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DendronautTestResultList.
func (in *DendronautTestResultList) DeepCopy() *DendronautTestResultList {
	if in == nil {
		return nil
	}
	out := new(DendronautTestResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DendronautTestResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DendronautTestResultSpec) DeepCopyInto(out *DendronautTestResultSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DendronautTestResultSpec.
func (in *DendronautTestResultSpec) DeepCopy() *DendronautTestResultSpec {
	if in == nil {
		return nil
	}
	out := new(DendronautTestResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DendronautTestResultStatus) DeepCopyInto(out *DendronautTestResultStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DendronautTestResultStatus.
func (in *DendronautTestResultStatus) DeepCopy() *DendronautTestResultStatus {
	if in == nil {
		return nil
	}
	out := new(DendronautTestResultStatus)
	in.DeepCopyInto(out)
	return out
}
